[workspace]
members = [
    "packages/battleship",
    "packages/battleship_web"
]
resolver = "3"

[workspace.package]
authors = ["Aaron Mathews <aamathews23@gmail.com>"]
homepage = "https://github.com/aamathews23/personal"
readme = "README.md"
repository = "https://github.com/aamathews23/personal"
edition = "2024"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
