#:schema node_modules/wrangler/config-schema.json
name = "aamathews23-personal"

main = "./server.ts"
workers_dev = true
compatibility_date = "2025-04-08"

[assets]
directory = "./build/client"

[build]
command = "pnpm build"