name: Web - Deploy
on:
  push:
    paths:
      - 'apps/web/**'
    branches:
      - main
jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm --filter web lint
      - name: Test
        run: pnpm --filter web test:coverage
      - name: Report Coverage
        if: always()
        uses:  davelosert/vitest-coverage-report-action@v2
        with:
          name: Web Coverage Report
          working-directory: apps/web
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: verify
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}